### ISSUE TITLE
Make https://www.http-feeds.org/inventory work

### ISSUE THREAD

**Issue by ewolff** [http-feeds/http-feeds#5]
The example on the homepage talks about an inventory example. If https://www.http-feeds.org/inventory would return that example, it might be helpful - just a static resource would be enough.

**Comment by jochenchrist** [comment]
Please double-check, the example should be working. There might be an initial delay until the Cloud Run instance starts up.
Note that the host of the examples is example.http-feeds.org: 
https://example.http-feeds.org/inventory

**Comment by ewolff** [comment]
Yes, works for me. Thanks for explaining!
